name: App build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build_unsigned:
    runs-on: macos-26

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build app without signing
        run: |
          xcodebuild \
            -project "Input Source Pro.xcodeproj" \
            -scheme "Input Source Pro" \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            clean build

      - name: Package app
        run: |
          ditto -c -k --sequesterRsrc --keepParent \
            "build/Build/Products/Release/Input Source Pro.app" \
            "Input Source Pro-unsigned.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Input Source Pro unsigned
          path: Input Source Pro-unsigned.zip
